<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RequestResponsePairs" nsURI="http://www.example.org/RequestResponsePairs"
    nsPrefix="RequestResponsePairs">
  <eClassifiers xsi:type="ecore:EClass" name="Roundtrip" instanceClassName="java.lang.Object">
    <eStructuralFeatures xsi:type="ecore:EReference" name="httprequest" lowerBound="1"
        eType="#//HttpRequest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="httpresponse" lowerBound="1"
        eType="#//HttpResponse" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roundtripName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HttpRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpMethod" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpRequestDatum" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiver" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HttpResponse" instanceTypeName="HttpResponse">
    <eStructuralFeatures xsi:type="ecore:EReference" name="httpresponsedatum" upperBound="-1"
        eType="#//HttpResponseDatum" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpStatus" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roundtrip" lowerBound="1"
        upperBound="-1" eType="#//Roundtrip" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scenarioName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HttpResponseDatum" instanceTypeName="ResponseDatum">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpResponseDatumName"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="httpResponseDatumXPath"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
