# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ttgrow: int=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param ttgrow: The ttgrow of this InlineResponse2002.  # noqa: E501
        :type ttgrow: int
        """
        self.swagger_types = {
            'ttgrow': int
        }

        self.attribute_map = {
            'ttgrow': 'ttgrow'
        }

        self._ttgrow = ttgrow

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ttgrow(self) -> int:
        """Gets the ttgrow of this InlineResponse2002.


        :return: The ttgrow of this InlineResponse2002.
        :rtype: int
        """
        return self._ttgrow

    @ttgrow.setter
    def ttgrow(self, ttgrow: int):
        """Sets the ttgrow of this InlineResponse2002.


        :param ttgrow: The ttgrow of this InlineResponse2002.
        :type ttgrow: int
        """
        if ttgrow is None:
            raise ValueError("Invalid value for `ttgrow`, must not be `None`")  # noqa: E501

        self._ttgrow = ttgrow
