# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, season: str=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param season: The season of this InlineResponse2001.  # noqa: E501
        :type season: str
        """
        self.swagger_types = {
            'season': str
        }

        self.attribute_map = {
            'season': 'season'
        }

        self._season = season

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def season(self) -> str:
        """Gets the season of this InlineResponse2001.


        :return: The season of this InlineResponse2001.
        :rtype: str
        """
        return self._season

    @season.setter
    def season(self, season: str):
        """Sets the season of this InlineResponse2001.


        :param season: The season of this InlineResponse2001.
        :type season: str
        """

        self._season = season
