# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Plant(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, plant_type: int=None):  # noqa: E501
        """Plant - a model defined in Swagger

        :param id: The id of this Plant.  # noqa: E501
        :type id: int
        :param plant_type: The plant_type of this Plant.  # noqa: E501
        :type plant_type: int
        """
        self.swagger_types = {
            'id': int,
            'plant_type': int
        }

        self.attribute_map = {
            'id': 'id',
            'plant_type': 'plant_type'
        }

        self._id = id
        self._plant_type = plant_type

    @classmethod
    def from_dict(cls, dikt) -> 'Plant':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Plant of this Plant.  # noqa: E501
        :rtype: Plant
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Plant.


        :return: The id of this Plant.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Plant.


        :param id: The id of this Plant.
        :type id: int
        """

        self._id = id

    @property
    def plant_type(self) -> int:
        """Gets the plant_type of this Plant.


        :return: The plant_type of this Plant.
        :rtype: int
        """
        return self._plant_type

    @plant_type.setter
    def plant_type(self, plant_type: int):
        """Sets the plant_type of this Plant.


        :param plant_type: The plant_type of this Plant.
        :type plant_type: int
        """

        self._plant_type = plant_type
