/*
 * generated by Xtext 2.18.0
 */
package plantuml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PumlStandaloneSetup extends PumlStandaloneSetupGenerated {

	def static void doSetup() {
		new PumlStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
