<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="configmetamodel" nsURI="http://www.example.org/configmetamodel"
    nsPrefix="configmetamodel">
  <eClassifiers xsi:type="ecore:EClass" name="ConfigList">
    <eStructuralFeatures xsi:type="ecore:EReference" name="asyncConfig" upperBound="-1"
        eType="#//AsyncRequestConfig"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AsyncRequestConfig">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseStatusCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestParameter" upperBound="-1"
        eType="#//RequestParameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responseParameter" upperBound="-1"
        eType="#//ResponseParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestVariableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseVariableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
