<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RestAssured" nsURI="http://www.example.org/RestAssured" nsPrefix="RestAssured">
  <eClassifiers xsi:type="ecore:EClass" name="TestRoundtrip" instanceTypeName="TestRoundtrip">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestspecification" lowerBound="1"
        eType="#//RequestSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsespecification"
        lowerBound="1" eType="#//ResponseSpecification" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testRoundtripName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precondition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestSpecification" instanceTypeName="RequestSpecification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiver" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestdatum" upperBound="-1"
        eType="#//RequestDatum" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseSpecification" instanceTypeName="ResponseSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodymatchergroup" eType="#//BodyMatcherGroup"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statusmatcher" eType="#//Matcher"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsedatum" upperBound="-1"
        eType="#//ResponseDatum" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodyMatcherGroup" instanceTypeName="BodyMatcherGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodymatcher" upperBound="-1"
        eType="#//BodyMatcher" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Matcher" instanceClassName="Matcher"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsIn" instanceClassName="IsIn" eSuperTypes="#//Matcher">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestScenario" instanceClassName="TestScenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testroundtrip" lowerBound="1"
        upperBound="-1" eType="#//TestRoundtrip" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="testScenarioName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HasXPath" eSuperTypes="#//Matcher">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BodyMatcher" instanceTypeName="BodyMatcher">
    <eStructuralFeatures xsi:type="ecore:EReference" name="matcher" lowerBound="1"
        eType="#//Matcher" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResponseDatum" instanceTypeName="ResponseDatum">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPath" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequestDatum" instanceTypeName="RequestDatum">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
