SEQUENCE @startuml

participant FA
participant GA
participant PL


FA -> GA : ["1"] POST "/garden/plant/${plantType}"
activate GA
GA -> FA : 200 - (plantId : "plantId")

GA -> PL : GET "/plant/season/${plantType}"
activate PL
PL -> GA : 200 - (season : "season")

FA -> GA : GET "/garden/seeds"
GA -> FA : 200

GA -> PL : GET "/plant/timetogrow/${plantType}"

PL -> GA : 200
deactivate PL

GA -> FA : ? POST "/farmer/grown" (plantID : "${plantId}")
FA -> GA : 200

deactivate GA

@enduml
