@startuml

participant "Farmer" as FA
participant "Garden" as GA
participant "Plant" as PL

activate FA

FA -> GA : POST "/garden/plant/${plantType1}"
activate GA
GA -> FA : 200 - (plantId1 : "plantId")

GA -> PL : GET "/plant/timetogrow/${plantType1}"
activate PL
PL -> GA : 200
deactivate PL

FA -> GA :  POST "/garden/plant/${plantType2}"
activate GA
GA -> FA : 200 - (plantId2 : "plantId")

GA -> PL : GET "/plant/timetogrow/${plantType2}"
activate PL
PL -> GA : 200
deactivate PL


GA -> FA : POST "/farmer/grown" (plantID : "${plantId1}")
FA -> GA : 200
deactivate GA

GA -> FA : POST "/farmer/grown" (plantID : "${plantId2}")
FA -> GA : 200
deactivate GA

deactivate FA

@enduml
