@startuml

participant "Farmer" as FA
participant "Garden" as GA
participant "Plant" as PL

activate FA

FA -> GA : POST "garden/plant/0"
activate GA
GA -> FA : 200 - (plantId : 1, plantType: 0)

GA -> PL: GET "plant/timetogrow/0"
activate PL
PL -> GA: 200 - (timetogrow: 90)
deactivate PL

FA -> GA : POST "garden/plant/1"
activate GA
GA -> FA : 200 - (plantId : 2, plantType: 1)

GA -> PL: GET "plant/timetogrow/1"
activate PL
PL -> GA: 200 - (timetogrow: 120)
deactivate PL


GA -> FA: POST "farmer/grown/0"
FA -> GA: 200
deactivate GA

GA -> FA: POST "farmer/grown/1"
FA -> GA: 200
deactivate GA

deactivate FA

@enduml
